### ISSUE TITLE
Button Icon Customisation

### ISSUE THREAD

**Issue by vignatov** [BlazorComponents/MatBlazor#34]
Is it possible to customise background and foreground colours of MatIconButton? I tried to use Class and Style, but they were ignored.

**Comment by SamProf** [comment]
Hi!
Thank you for your request.

It's fixed in version MatBlazor 0.6.2.
You can use Class and Style parameters for customizing buttons.
Example: https://blazorcomponents.github.io/MatBlazor/BaseMatComponent

I see that MatIconButton is not rounded, it;s will be fixed later, but now using style you can change what you want.

If you want some new features - please create new tasks.
Thank you.
