### ISSUE TITLE
CheckBox in CompnentBase Class

### ISSUE THREAD

**Issue by enkodellc** [BlazorComponents/MatBlazor#41]
> Error: System.InvalidOperationException: Object of type 'MatBlazor.Components.MatCheckbox.MatCheckbox' does not have a property matching the name 'ChildContent'

Error when using checkbox in a page when the page inherits a class with the ComponentBase class. It looks like this parameter is missing. I am submitting a PR for it now. I am not 100% if other components need this as well. 

Also I am getting the error in my app and was able to recreate it in the MatBlazor.Demo.App.

**Comment by SamProf** [comment]
That's strange, because I can not reproduce your error if I remove ChildContent parameter from BaseMatCheckbox.
I think that the problem not in INheritance.
You just try put something inside MatCheckBox element and this is not supported.
This code produce your error, but this is right.

`<MatCheckbox bind-Checked="@MyCheck" class="filled-in chk-col-blue">You put something here, but you shouldn't</MatCheckbox>
`

**Comment by SamProf** [comment]
Maybe I will allow ChildContent for MatCheckBox for Label.
Right now Label - only is Parameter.

**Comment by enkodellc** [comment]
Oh yes, that is the issue. My error. Was working too late and didn't figure that out.  Angular Material allows for the Label as a Child Element and I attempting to convert some of my Angular to Blazor. So do you want me to update my PR to allow for the checkbox Label / ChildContent?

**Comment by SamProf** [comment]
Your PR very big and with example of  this issue.
Maybe it's better to reject this changes.
But yes - if you want contrubute, you can add Parameter childcontent to CheckBox and render ChildContent near label and make new PR.
Thank you.
